<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFSfuOAk\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFSfuOAk/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFSfuOAk.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerFSfuOAk\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerFSfuOAk\srcProdProjectContainer(array(
    'container.build_hash' => 'FSfuOAk',
    'container.build_id' => 'dfa09905',
    'container.build_time' => 1515597824,
));
