<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGS2Jx86\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGS2Jx86/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGS2Jx86.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGS2Jx86\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerGS2Jx86\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'GS2Jx86',
    'container.build_id' => 'e5a56d29',
    'container.build_time' => 1516054580,
));
